### ISSUE TITLE
fwknopd not working with nftables

### ISSUE THREAD

**Issue by geo99918** [mrash/fwknop#352] opened 2023-05-31 12:39 UTC
fwknopd is not working with newer kernels that use nftables.

see: https://forum.openwrt.org/t/fwknop-on-x86-64-22-03-2/143855

**Comment by bam80** [comment] 2023-06-06 12:14
This probably is a duplicate of #107

**Comment by davidandreoletti** [comment] 2023-06-14 18:30
@mrash This is definitely a duplicate of #107. Would you mind closing #352 ?

**Comment by mrash** [comment] 2023-06-15 02:17
Yes, agreed, closing this one as a dupe of #107.

**Closed by mrash** 2023-06-15 02:17 UTC
